FROM node:20-alpine AS builder
WORKDIR /app

COPY package.json ./
# 如果有 package-lock.json 就用它；没有也没关系
RUN npm config set registry https://registry.npmmirror.com
RUN npm install --legacy-peer-deps


COPY . .
# 关键：先跳过 vue-tsc，只做 vite build
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
