"""add_capability_generation

Revision ID: 7a1daa2277d7
Revises: aa9ef32785c8
Create Date: 2026-05-17 12:28:53.775461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a1daa2277d7'
down_revision: Union[str, None] = 'aa9ef32785c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('capabilities', sa.Column('current_production_generation_id', sa.Integer(), nullable=True))
    op.add_column('capabilities', sa.Column('current_research_generation_id', sa.Integer(), nullable=True))
    op.add_column('capabilities', sa.Column('next_planning_generation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'capabilities', 'capability_generations', ['next_planning_generation_id'], ['id'])
    op.create_foreign_key(None, 'capabilities', 'capability_generations', ['current_research_generation_id'], ['id'])
    op.create_foreign_key(None, 'capabilities', 'capability_generations', ['current_production_generation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'capabilities', type_='foreignkey')
    op.drop_constraint(None, 'capabilities', type_='foreignkey')
    op.drop_constraint(None, 'capabilities', type_='foreignkey')
    op.drop_column('capabilities', 'next_planning_generation_id')
    op.drop_column('capabilities', 'current_research_generation_id')
    op.drop_column('capabilities', 'current_production_generation_id')
    # ### end Alembic commands ###
