"""initial

Revision ID: 9d00d28d8ea0
Revises: 
Create Date: 2026-05-17 10:58:13.818044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d00d28d8ea0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('product_line', sa.Enum('HUD', 'LIGHT', 'PROJECTION', 'ALL', name='productline'), nullable=False),
    sa.Column('capability_type', sa.Enum('DISPLAY_ALGO', 'SPATIAL_STABILITY', 'PERCEPTION_FUSION', 'PARAM_GENERALIZATION', 'REALTIME_PERFORMANCE', 'CALIBRATION_CONSISTENCY', 'ENGINEERING_FRAMEWORK', 'INTERACTION_EXPRESSION', name='capabilitytype'), nullable=False),
    sa.Column('maturity_level', sa.Enum('L1', 'L2', 'L3', 'L4', 'L5', name='maturitylevel'), nullable=False),
    sa.Column('risk_status', sa.Enum('NORMAL', 'WATCH', 'HIGH_RISK', name='riskstatus'), nullable=False),
    sa.Column('maturity_evidence', sa.Text(), nullable=True),
    sa.Column('capability_gaps', sa.Text(), nullable=True),
    sa.Column('gap_actions', sa.Text(), nullable=True),
    sa.Column('knowledge_records', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('backup_owner_id', sa.Integer(), nullable=True),
    sa.Column('responsibility_field_id', sa.Integer(), nullable=True),
    sa.Column('responsibility_field_name', sa.String(length=200), nullable=True),
    sa.Column('support_member_ids', sa.String(length=500), nullable=True),
    sa.Column('hr_risk_note', sa.Text(), nullable=True),
    sa.Column('care_scope', sa.Text(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['backup_owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capabilities_capability_type'), 'capabilities', ['capability_type'], unique=False)
    op.create_index(op.f('ix_capabilities_id'), 'capabilities', ['id'], unique=False)
    op.create_index(op.f('ix_capabilities_maturity_level'), 'capabilities', ['maturity_level'], unique=False)
    op.create_index(op.f('ix_capabilities_name'), 'capabilities', ['name'], unique=False)
    op.create_index(op.f('ix_capabilities_owner_id'), 'capabilities', ['owner_id'], unique=False)
    op.create_index(op.f('ix_capabilities_product_line'), 'capabilities', ['product_line'], unique=False)
    op.create_index(op.f('ix_capabilities_risk_status'), 'capabilities', ['risk_status'], unique=False)
    op.create_table('delivery_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('product_line', sa.Enum('HUD', 'LIGHT', 'PROJECTION', 'ALL', name='productline'), nullable=False),
    sa.Column('project_name', sa.String(length=200), nullable=True),
    sa.Column('priority', sa.Enum('P0', 'P1', 'P2', name='issuepriority'), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'ANALYZING', 'FIXING', 'VERIFYING', 'CLOSED', name='issuestatus'), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('impact', sa.Text(), nullable=True),
    sa.Column('latest_progress', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_issues_id'), 'delivery_issues', ['id'], unique=False)
    op.create_index(op.f('ix_delivery_issues_priority'), 'delivery_issues', ['priority'], unique=False)
    op.create_index(op.f('ix_delivery_issues_product_line'), 'delivery_issues', ['product_line'], unique=False)
    op.create_index(op.f('ix_delivery_issues_status'), 'delivery_issues', ['status'], unique=False)
    op.create_table('capability_issues',
    sa.Column('capability_id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ),
    sa.ForeignKeyConstraint(['issue_id'], ['delivery_issues.id'], ),
    sa.PrimaryKeyConstraint('capability_id', 'issue_id')
    )
    op.create_table('capability_topics',
    sa.Column('capability_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('capability_id', 'topic_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('capability_topics')
    op.drop_table('capability_issues')
    op.drop_index(op.f('ix_delivery_issues_status'), table_name='delivery_issues')
    op.drop_index(op.f('ix_delivery_issues_product_line'), table_name='delivery_issues')
    op.drop_index(op.f('ix_delivery_issues_priority'), table_name='delivery_issues')
    op.drop_index(op.f('ix_delivery_issues_id'), table_name='delivery_issues')
    op.drop_table('delivery_issues')
    op.drop_index(op.f('ix_capabilities_risk_status'), table_name='capabilities')
    op.drop_index(op.f('ix_capabilities_product_line'), table_name='capabilities')
    op.drop_index(op.f('ix_capabilities_owner_id'), table_name='capabilities')
    op.drop_index(op.f('ix_capabilities_name'), table_name='capabilities')
    op.drop_index(op.f('ix_capabilities_maturity_level'), table_name='capabilities')
    op.drop_index(op.f('ix_capabilities_id'), table_name='capabilities')
    op.drop_index(op.f('ix_capabilities_capability_type'), table_name='capabilities')
    op.drop_table('capabilities')
    # ### end Alembic commands ###
