"""add_capability_category_tree

Revision ID: aa9ef32785c8
Revises: 9d00d28d8ea0
Create Date: 2026-05-17 11:57:33.148454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa9ef32785c8'
down_revision: Union[str, None] = '9d00d28d8ea0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('capabilities', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_capabilities_category_id'), 'capabilities', ['category_id'], unique=False)
    op.create_foreign_key(None, 'capabilities', 'capability_categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'capabilities', type_='foreignkey')
    op.drop_index(op.f('ix_capabilities_category_id'), table_name='capabilities')
    op.drop_column('capabilities', 'category_id')
    # ### end Alembic commands ###
