"""add_generation_id_to_delivery_issues

Revision ID: ab85d208446b
Revises: cc72f3445fd7
Create Date: 2026-05-17 14:32:01.744707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab85d208446b'
down_revision: Union[str, None] = 'cc72f3445fd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_issues', sa.Column('generation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'delivery_issues', 'capability_generations', ['generation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'delivery_issues', type_='foreignkey')
    op.drop_column('delivery_issues', 'generation_id')
    # ### end Alembic commands ###
