"""add_knowledge_wiki_page_ids_and_restructure_categories

Revision ID: cc72f3445fd7
Revises: 7a1daa2277d7
Create Date: 2026-05-17 13:00:14.389999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc72f3445fd7'
down_revision: Union[str, None] = '7a1daa2277d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('capabilities', sa.Column('knowledge_wiki_page_ids', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('capabilities', 'knowledge_wiki_page_ids')
    # ### end Alembic commands ###
